### ISSUE TITLE
Function::getName() returns nullptr right after Module->addFunction() on macOS Big Sur

### ISSUE THREAD

**Issue by clns** [rAzoR8/SpvGenTwo#40]
`spvgentwo::Function::getName()` returns a `nullptr` and results in a "*Segmentation fault: 11*" crash on macOS Big Sur 11.6 with Xcode 13.0.

The code to reproduce:

```c++
spvgentwo::HeapAllocator alloc;
spvgentwo::Module module(&alloc);
spvgentwo::Function& funcAdd = module.addFunction("add", spvgentwo::spv::FunctionControlMask::Const);
const char* name = funcAdd.getName(); // returns nullptr
if (name == nullptr) {
    // name is nullptr
}
```

So if you do for example `std::string(funcAdd.getName())` it will result in a seg fault.

Anyone experiencing this problem on macOS? This actually happens in SHADERed here: https://github.com/dfranx/SHADERed/issues/256#issuecomment-949072217

**Comment by rAzoR8** [comment]
fixed with https://github.com/rAzoR8/SpvGenTwo/commit/fe107be7422294f4ee98790815106dda83d8d95a
